# Site settings
title: Satyam Khanna  
description: R&D Engineer & Tinkerer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Satyam Khanna
user_description: Embedded Engineer with a experience in developing Commercial, Industrial, Medical applications. Skilled in Embedded Systems, PCB Design, C++, ARM, PIC,
8051, AVR, Product Design. Familiar with latest Architectures and Developments.
user_title: Embedded Engineer
email: satyamkhanna66@gmail.com
# twitter_username: 
github_username:  electronsoul
linkedin_username : skhanna23
#acebook_username : 

exclude: ['package.json', 'src' , 'node_modules']
